//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class COFFAPPROVAL
    {
        public string APPLICATIONNO { get; set; }
        public System.DateTime DAY { get; set; }
        public Nullable<double> APPROVED_HRS { get; set; }
        public string APPROVED { get; set; }
    }
}
