//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_WEEKLYOFF
    {
        public int ID { get; set; }
        public string EMP_ID { get; set; }
        public string WEEKLY_OFF1 { get; set; }
        public string WEEKLY_OFF1_DAYS { get; set; }
        public string WEEKLY_OFF2 { get; set; }
        public string WEEKLY_OFF2_DAYS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
    }
}
