//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEEMASTER
    {
        public string EMP_ID { get; set; }
        public string TITLE { get; set; }
        public string FNAME { get; set; }
        public string MNAME { get; set; }
        public string LNAME { get; set; }
        public string EMPLOYMENT_TYPE { get; set; }
        public System.DateTime DOJ { get; set; }
        public string SEX { get; set; }
        public string DESIGNATION_ID { get; set; }
        public string GRADE_ID { get; set; }
        public string DEPTNO { get; set; }
        public string LOCATION_ID { get; set; }
        public string SECTION_ID { get; set; }
        public Nullable<double> BASIC_SAL { get; set; }
        public string PAYMENT_BY { get; set; }
        public string WEEKLY_OFF { get; set; }
        public string CONTRACT_ID { get; set; }
        public Nullable<System.DateTime> DATE_OF_RESIG_TERMIN { get; set; }
        public Nullable<System.DateTime> RESIGN_ON { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ADDRESS { get; set; }
        public string MARRIED { get; set; }
        public string NOMINEE_NAME { get; set; }
        public string NOMINEE_ADDRESS { get; set; }
        public string RELATION { get; set; }
        public string PHONE_NO { get; set; }
        public string PASSPORT_NO { get; set; }
        public string SKILLED_UNSKILLED { get; set; }
        public string STATUS { get; set; }
        public Nullable<double> OT_RATE { get; set; }
        public string ESIAPPLICABLE { get; set; }
        public string PFAPPLICABLE { get; set; }
        public string ESINO { get; set; }
        public string PFNO { get; set; }
        public string ACCOUNTNO { get; set; }
        public string BANKNAME { get; set; }
        public string SERIALNO { get; set; }
        public string LOGINID { get; set; }
        public string PASSWORD { get; set; }
        public string MGRID { get; set; }
        public string PAY_CODE { get; set; }
        public string OT_ID { get; set; }
        public string LATE_ID { get; set; }
        public string CHEQUE_NO { get; set; }
        public Nullable<System.DateTime> CHEQUE_DATE { get; set; }
        public string PTAPPLICABLE { get; set; }
        public string ESIDATE { get; set; }
        public string EMAIL_ID { get; set; }
        public string EMPPHOTO { get; set; }
        public string PHONE_OFF { get; set; }
        public string EXT { get; set; }
        public string MOBILENO { get; set; }
        public string BYALPHA { get; set; }
        public Nullable<double> BYNUMBER { get; set; }
        public string UNIONID { get; set; }
        public Nullable<double> HRID { get; set; }
        public Nullable<System.DateTime> JMONTH { get; set; }
        public Nullable<System.DateTime> RMONTH { get; set; }
        public string COID { get; set; }
        public string JVLOC_ID { get; set; }
        public byte[] PhotoData { get; set; }
        public string CDesigID { get; set; }
        public string Aadhaar { get; set; }
        public string AEID { get; set; }
        public string emPhone { get; set; }
        public string emContact { get; set; }
        public string PERMANENTADDRESS { get; set; }
        public string leaveauthority { get; set; }
        public string PANNO { get; set; }
        public Nullable<System.DateTime> PASSWORD_CHANGE_DATE { get; set; }
        public Nullable<int> FAILURE_ATTEMPTS { get; set; }
        public Nullable<bool> IS_LOCKED { get; set; }
        public string EPSApplicable { get; set; }
        public Nullable<System.DateTime> dtFinalSettlement { get; set; }
        public Nullable<decimal> hiQual { get; set; }
        public Nullable<decimal> Handicap { get; set; }
        public string IFSCCODE { get; set; }
        public Nullable<System.DateTime> ESI_END_MONTH { get; set; }
        public string BANK_BRANCH { get; set; }
        public string SSID { get; set; }
        public Nullable<double> annualsalary { get; set; }
        public string weekly_off1 { get; set; }
        public Nullable<System.DateTime> Passport_Date { get; set; }
        public string IsTrgerFired { get; set; }
        public string ReasonForResign { get; set; }
        public string PersonalEmail { get; set; }
        public Nullable<System.DateTime> Address_change_date { get; set; }
        public string CTC_PERIOD { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
        public string FNF_STATUS { get; set; }
        public string NPS_APPLICABLE { get; set; }
        public Nullable<double> NPS_PERCENTAGE { get; set; }
        public string PortalAccessble { get; set; }
        public string SwipeAttendance { get; set; }
        public string EmergencyRelation { get; set; }
        public string BeneficiaryName { get; set; }
    }
}
