//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCASHPROCESS
    {
        public string EMP_ID { get; set; }
        public System.DateTime MONTH { get; set; }
        public Nullable<double> ENCASHMENT_DAYS { get; set; }
        public string PREF1 { get; set; }
        public string PREF2 { get; set; }
        public string PREF3 { get; set; }
        public Nullable<double> DAYS_DEDUCT1 { get; set; }
        public Nullable<double> DAYS_DEDUCT2 { get; set; }
        public Nullable<double> DAYS_DEDUCT3 { get; set; }
        public string EPREF1 { get; set; }
        public string EPREF2 { get; set; }
        public string EPREF3 { get; set; }
        public Nullable<double> EDAYS_DEDUCT1 { get; set; }
        public Nullable<double> EDAYS_DEDUCT2 { get; set; }
        public Nullable<double> EDAYS_DEDUCT3 { get; set; }
        public Nullable<System.DateTime> PAYPERIODSTART { get; set; }
        public Nullable<System.DateTime> PAYPERIODEND { get; set; }
        public Nullable<System.DateTime> ATTENSTART { get; set; }
        public Nullable<System.DateTime> ATTENEND { get; set; }
    }
}
