//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEAVEENCASHMENT
    {
        public string APP_NO { get; set; }
        public System.DateTime DATE1 { get; set; }
        public string EMP_ID { get; set; }
        public string LEAVE_TYPE { get; set; }
        public double ENCASHING_DAYS { get; set; }
        public string APPROVED { get; set; }
        public string APPROVEDBY { get; set; }
        public string REMARKS { get; set; }
        public Nullable<System.DateTime> MONTHENCASHED { get; set; }
        public Nullable<double> MSGNO { get; set; }
        public Nullable<System.DateTime> APPROVEDDATE { get; set; }
    }
}
