//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class linkLeaveLoc
    {
        public long ID { get; set; }
        public string LeaveID { get; set; }
        public string LocID { get; set; }
        public Nullable<System.DateTime> EffectDate { get; set; }
    }
}
