//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ANil_July_2018Entities : DbContext
    {
        public ANil_July_2018Entities()
            : base("name=ANil_July_2018Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COFFAPPROVAL> COFFAPPROVALs { get; set; }
        public virtual DbSet<EMP_WEEKLYOFF> EMP_WEEKLYOFF { get; set; }
        public virtual DbSet<EMPLOYEELEAVEDETAIL> EMPLOYEELEAVEDETAILS { get; set; }
        public virtual DbSet<EMPLOYEEMASTER> EMPLOYEEMASTERs { get; set; }
        public virtual DbSet<ENCASHPROCESS> ENCASHPROCESSes { get; set; }
        public virtual DbSet<LEAVEAPPAPPROVAL> LEAVEAPPAPPROVALs { get; set; }
        public virtual DbSet<LEAVEENCASHMENT> LEAVEENCASHMENTs { get; set; }
        public virtual DbSet<LEAVEGRADELINK> LEAVEGRADELINKs { get; set; }
        public virtual DbSet<LEAVEMASTER> LEAVEMASTERs { get; set; }
        public virtual DbSet<linkLeaveLoc> linkLeaveLocs { get; set; }
        public virtual DbSet<MONTHEND_LEAVEBAL> MONTHEND_LEAVEBAL { get; set; }
        public virtual DbSet<MONTHLYATTENDANCE> MONTHLYATTENDANCEs { get; set; }
        public virtual DbSet<OTCOFFHR> OTCOFFHRS { get; set; }
        public virtual DbSet<PAYPERIODDEFINITION> PAYPERIODDEFINITIONs { get; set; }
        public virtual DbSet<Payroll_LOG> Payroll_LOG { get; set; }
    }
}
