//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTHEND_LEAVEBAL
    {
        public string EMP_ID { get; set; }
        public System.DateTime MONTH { get; set; }
        public string LEAVE_ID { get; set; }
        public string START_CLOSE { get; set; }
        public Nullable<double> O_BAL { get; set; }
        public Nullable<double> ACCRUED { get; set; }
        public Nullable<double> UTILIZED { get; set; }
        public Nullable<double> ENCASHED { get; set; }
        public Nullable<double> AUTILIZED { get; set; }
    }
}
