//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTHLYATTENDANCE
    {
        public string EMP_ID { get; set; }
        public System.DateTime MONTH { get; set; }
        public double TOTAL_DAYS { get; set; }
        public double NO_OF_WORKING_DAYS { get; set; }
        public double DAYS_WORKED { get; set; }
        public string SPECIAL_SHIFT { get; set; }
        public Nullable<double> LATE_DAYS { get; set; }
        public Nullable<double> OT_HOURS { get; set; }
        public Nullable<double> LATE_DAYS1 { get; set; }
        public Nullable<double> LATE_DAYS2 { get; set; }
        public string FLAG { get; set; }
        public string PUNCH_FLAG { get; set; }
        public Nullable<double> LOSS_OF_PAY { get; set; }
        public Nullable<double> SHIFT_DAYS { get; set; }
        public Nullable<double> EARLYDAYS1 { get; set; }
        public Nullable<double> EARLYDAYS2 { get; set; }
        public Nullable<double> EARLYDAYS3 { get; set; }
        public Nullable<double> LDEDUCTDAYS { get; set; }
        public Nullable<double> EDEDUCTDAYS { get; set; }
        public Nullable<double> NOJDEDUCTDAYS { get; set; }
        public Nullable<double> LATEDAYSDEDUCT { get; set; }
        public Nullable<double> EARLYDAYSDEDUCT { get; set; }
        public string VERSIONFLAG { get; set; }
        public Nullable<double> WOFFOTHRS { get; set; }
        public Nullable<double> HOLOTHRS { get; set; }
        public Nullable<double> WOFFDAYS { get; set; }
        public Nullable<double> HOLIDAYS { get; set; }
        public Nullable<double> PAY_TDAYS { get; set; }
        public string STATUS { get; set; }
        public Nullable<decimal> IncentiveHrs { get; set; }
        public Nullable<double> LEAVES { get; set; }
        public Nullable<double> UnpaidLeave { get; set; }
    }
}
