//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYPERIODDEFINITION
    {
        public string PAY_CODE { get; set; }
        public Nullable<double> CLOSING_DATE { get; set; }
        public Nullable<double> PAY_DATE { get; set; }
        public System.DateTime PAY_FROMDATE { get; set; }
        public Nullable<double> SAL_DATE { get; set; }
        public Nullable<double> ATTEN_DATE { get; set; }
    }
}
