//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payroll_LOG
    {
        public int id { get; set; }
        public string SelMonth { get; set; }
        public string type1 { get; set; }
        public string server1 { get; set; }
        public string database1 { get; set; }
        public string dbUName { get; set; }
        public string dbPass { get; set; }
        public string SelectedEmployees { get; set; }
        public string ByRef { get; set; }
        public string Source { get; set; }
    }
}
